// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWBlZ7yCPb-p90ASyMnuVV9ijo1QzgFDw',
    appId: '1:68673754284:web:0a3e35235aea4c761a7b09',
    messagingSenderId: '68673754284',
    projectId: 'sharemind-f7c1d',
    authDomain: 'sharemind-f7c1d.firebaseapp.com',
    storageBucket: 'sharemind-f7c1d.firebasestorage.app',
    measurementId: 'G-27VWHFVD19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHAuUtRNN9AGpKyeXayawW5oENR6UMNZE',
    appId: '1:68673754284:android:19e49315863aa9951a7b09',
    messagingSenderId: '68673754284',
    projectId: 'sharemind-f7c1d',
    storageBucket: 'sharemind-f7c1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJWO5mSS89PbxoORM4WShkYfpk2hkYgmE',
    appId: '1:68673754284:ios:636ac027141a05b61a7b09',
    messagingSenderId: '68673754284',
    projectId: 'sharemind-f7c1d',
    storageBucket: 'sharemind-f7c1d.firebasestorage.app',
    iosClientId: '68673754284-sc4hld7e1as78qqufci0our9cl9gv0mm.apps.googleusercontent.com',
    iosBundleId: 'com.example.huangBoxManagerWeb',
  );
}
